package config

import "fmt"

func RegisterTrackA(r *Registry) error {
	if r == nil {
		return fmt.Errorf("registry must not be nil")
	}

	entries := []Entry{
		{
			Key:         "email.from",
			Type:        TypeString,
			Default:     "",
			Description: "SMTP 发件人地址，留空表示禁用邮件发送",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_EMAIL_FROM"},
		},
		{
			Key:         "email.smtp_host",
			Type:        TypeString,
			Default:     "",
			Description: "SMTP Host",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SMTP_HOST"},
		},
		{
			Key:         "email.smtp_port",
			Type:        TypeInt,
			Default:     "587",
			Description: "SMTP 端口",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SMTP_PORT"},
		},
		{
			Key:         "email.smtp_user",
			Type:        TypeString,
			Default:     "",
			Description: "SMTP 用户名",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SMTP_USER"},
		},
		{
			Key:         "email.smtp_pass",
			Type:        TypeString,
			Default:     "",
			Description: "SMTP 密码",
			Sensitive:   true,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SMTP_PASS"},
		},
		{
			Key:         "email.smtp_tls_mode",
			Type:        TypeString,
			Default:     "starttls",
			Description: "SMTP TLS 模式：starttls/tls/none",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SMTP_TLS_MODE"},
		},

		{
			Key:         "openviking.base_url",
			Type:        TypeString,
			Default:     "",
			Description: "OpenViking Base URL",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "openviking.root_api_key",
			Type:        TypeString,
			Default:     "",
			Description: "OpenViking Root API Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
		},
		{
			Key:         "openviking.cost_per_commit",
			Type:        TypeNumber,
			Default:     "0",
			Description: "OpenViking CommitSession Cost (USD)",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "nowledge.base_url",
			Type:        TypeString,
			Default:     "",
			Description: "Nowledge Base URL",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_NOWLEDGE_BASE_URL"},
		},
		{
			Key:         "nowledge.api_key",
			Type:        TypeString,
			Default:     "",
			Description: "Nowledge API Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_NOWLEDGE_API_KEY"},
		},
		{
			Key:         "nowledge.request_timeout_ms",
			Type:        TypeInt,
			Default:     "30000",
			Description: "Nowledge request timeout in milliseconds",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_NOWLEDGE_REQUEST_TIMEOUT_MS"},
		},

		{
			Key:         "turnstile.secret_key",
			Type:        TypeString,
			Default:     "",
			Description: "Turnstile Secret Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
		},
		{
			Key:         "turnstile.site_key",
			Type:        TypeString,
			Default:     "",
			Description: "Turnstile Site Key",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "turnstile.allowed_host",
			Type:        TypeString,
			Default:     "",
			Description: "Turnstile Allowed Host",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "gateway.ip_mode",
			Type:        TypeString,
			Default:     "direct",
			Description: "Gateway IP 模式：direct/cloudflare/trusted_proxy",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "gateway.trusted_cidrs",
			Type:        TypeString,
			Default:     "",
			Description: "Gateway 可信代理 CIDR 列表",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "gateway.risk_reject_threshold",
			Type:        TypeInt,
			Default:     "0",
			Description: "Gateway 风险拒绝阈值（0-100）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "gateway.ratelimit_capacity",
			Type:        TypeNumber,
			Default:     "600",
			Description: "Gateway Rate Limit Capacity",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_RATELIMIT_CAPACITY"},
		},
		{
			Key:         "gateway.ratelimit_rate_per_minute",
			Type:        TypeNumber,
			Default:     "300",
			Description: "Gateway Rate Limit Per Minute",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_RATELIMIT_RATE_PER_MINUTE"},
		},

		{
			Key:         "llm.retry.max_attempts",
			Type:        TypeInt,
			Default:     "10",
			Description: "LLM 重试最大次数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "llm.retry.base_delay_ms",
			Type:        TypeInt,
			Default:     "1000",
			Description: "LLM 重试基础延迟（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "security.injection_scan.regex_enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "Regex Scanner 开关",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.injection_scan.trust_source_enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "Trust Source 标记开关",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.injection_scan.semantic_enabled",
			Type:        TypeBool,
			Default:     "false",
			Description: "Prompt Guard 语义扫描开关",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.semantic_scanner.provider",
			Type:        TypeString,
			Default:     "",
			Description: "语义扫描提供方（留空 / local / api）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.semantic_scanner.api_endpoint",
			Type:        TypeString,
			Default:     "",
			Description: "远端语义扫描服务地址（OpenAI 兼容 /chat/completions）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.semantic_scanner.api_key",
			Type:        TypeString,
			Default:     "",
			Description: "远端语义扫描服务 API Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.semantic_scanner.api_model",
			Type:        TypeString,
			Default:     "openai/gpt-oss-safeguard-20b",
			Description: "远端语义扫描模型标识",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.semantic_scanner.api_timeout_ms",
			Type:        TypeInt,
			Default:     "4000",
			Description: "远端语义扫描超时（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.injection_scan.blocking_enabled",
			Type:        TypeBool,
			Default:     "false",
			Description: "检测到注入时直接拦截请求",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "security.injection_scan.tool_output_scan_enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "扫描工具输出中的间接注入",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
	}

	for _, e := range entries {
		if err := r.Register(e); err != nil {
			return err
		}
	}
	return nil
}
